### ISSUE TITLE
`assert_mutability!` is being renamed to `assert_modifiable!`

### ISSUE THREAD

**Issue by ghiculescu** [salsify/goldiloader#150]
See https://github.com/rails/rails/pull/52320

This means goldiloader crashes against edge rails, here: https://github.com/salsify/goldiloader/blob/92269d7318afe9f8d6f0719299709a7d8831c58a/lib/goldiloader/active_record_patches.rb#L59

**Comment by jturkel** [comment]
Thanks for reporting this @ghiculescu! It's fixed on `master` now.
