### ISSUE TITLE
New release that allows testing against rails main?

### ISSUE THREAD

**Issue by kyrofa** [salsify/goldiloader#154]
Part of our CI process for our gems runs against Rails' main branch in github. One of our gems depends upon goldiloader, and the latest release only supports Rails 7, so we can't actually do that. Looks like the gemspec in master currently supports Rails `'>= 6.1', '< 8.1'`, but that's not actually contained in a release. Any chance you're up for cutting one?

Side note: Rails 8 of course isn't actually released yet. Rails main is currently at 8.0.0.alpha. Today the gemspec claims compatibility with Rails 8.0.0 (because of the `< 8.1`), but in case you're unaware, it doesn't have to: it could simply say `< 8`. 8.0.0.alpha is > 7, but < 8. That would allow testing against v8 pre-releases without actually claiming compatibility with Rails 8. You probably know this, just wanted to throw it out there in case you didn't.

**Comment by kyrofa** [comment]
By the way, Rails 7.2 is released now. There is no released version of goldiloader that is compatible with that, either.

**Comment by jturkel** [comment]
@kyrofa - The changes have been released in 5.3.0. Thanks for the tip on the gemspec version constraint! I was not aware of that.

**Comment by kyrofa** [comment]
Thanks @jturkel! I'll go happily uncomment some appraisals now :smile: .
