### ISSUE TITLE
Not loading has_one resources

### ISSUE THREAD

**Issue by juanpastas** [salsify/goldiloader#25]
I tried with a discussion class which:

```ruby
	has_one :content, through: :assignment
	has_one :classroom, through: :assignment
	belongs_to :topic
```

And I got several queries for the first two. Topic is fine.

**Comment by jturkel** [comment]
@juanpastas - Do you have a small reproducible test case for this problem?

**Comment by juanpastas** [comment]
How could I create one? doing a Rails app?

**Comment by jturkel** [comment]
The easiest reproducible test cases to work with are gists that use the [Active Record bug template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb) (you'll have to update the gem section to include goldiloader).

In the meantime can you answer a few questions on the issue you're seeing:

* What version of Active Record and Goldiloader are you using?
* What is the error message + stack trace you're seeing? 
* How is the `assignment` association defined?
* Does the problem still reproduce if you take Goldiloader out of your app and just use standard Rails eager loading?

**Comment by juanpastas** [comment]
- Rails 4.2.2, latest version of goldiloader
- I am using bullet gem to report N+1 queries, so I see the message on the page and rails server logger.
-  `belongs_to :assignment, counter_cache: true`
- Problem disappears when I use `current_user.discussions.includes(:classroom, :content, :topic)` and delete gem from Gemfile.

**Comment by jturkel** [comment]
@juanpastas - I couldn't reproduce this problem. I focused on the `content` and `assignment` associations and everything worked fine. The test can be found [here](https://gist.github.com/jturkel/9ff605075ca25248f063). Can you take a look and see if you can reproduce the problem?

**Comment by juanpastas** [comment]
I [tried](https://github.com/juanpastas/goldiloader_has_one) too, but I could not reproduce it. I should have done something wrong.
