### ISSUE TITLE
ActiveRecord 5.0 Support

### ISSUE THREAD

**Issue by jturkel** [salsify/goldiloader#27]
This is issue is to track progress towards ActiveRecord 5.0 support.

**Comment by jturkel** [comment]
This work is being done on the `feature/rails-5` branch. Work includes:

- [x] Gemspec and Travis updates
- [x] Fix registration of association options
- [ ] Fix tests with overridden `from` clause
- [ ] Compare ActiveRecord 4.2 and 5.0 for any interesting changes we should be aware of
- [ ] Fix `alias_method_chain` deprecation
- [ ] Get Rails 5 unit tests passing with Goldiloader

**Comment by jturkel** [comment]
It looks like customizing the `from` of an association's scope is broken in Rails 5 causing two Goldiloader test failures. See https://github.com/rails/rails/issues/22996.

**Comment by jturkel** [comment]
Database cleaner is generating a deprecation warning when running tests in Rails 5. See https://github.com/DatabaseCleaner/database_cleaner/issues/412.

**Comment by jturkel** [comment]
Initial Rails 5 support added in 1d1ba60

**Comment by Tongboy** [comment]
@jturkel any help you need on this? I'm happy to help if there is. Goldiloader is our last gem dependency preventing our upgrade to rails 5 and it looks like we're facing issues based on the `from` customization.

**Comment by jturkel** [comment]
@Tongboy - This issue should have been closed awhile ago because Goldiloader *should* work fine with Rails 5. The customization of the `from` clause was fixed in https://github.com/rails/rails/commit/f138bea5da463509c0dc51283dd35e803796a77a which went into Rails 5.0.0. Can you file a new issue (with a reproducible test case) if you're still seeing any issues with Rails 5? Thanks.
