### ISSUE TITLE
auto_include: false isn't honored with HABTM

### ISSUE THREAD

**Issue by gavri** [salsify/goldiloader#34]
https://github.com/gavri/goldiloader/commit/faad9758b52c3066b14da568340c77a5da0d2bdf

**Comment by jturkel** [comment]
Looks like as of Rails 4.1 `has_and_belongs_to_many` creates a `has_many` association under the covers and the `auto_include` option isn't propagated to this association. Rails 3.2 and 4.0 are unaffected. I'm working on a fix.

**Comment by gavri** [comment]
Thanks!
