### ISSUE TITLE
Rails 5 belongs_to validation skipped

### ISSUE THREAD

**Issue by coorasse** [salsify/goldiloader#41]
When I include `goldiloader` gem in my application the Rails 5 validation on belongs_to association is skipped and not performed.

**Comment by jturkel** [comment]
@coorasse - I wasn't able to reproduce this issue. My test case can be found in https://gist.github.com/jturkel/5aea783a05dbfc2b345132580e78921c. Can you modify this test case to reproduce the issue?

**Comment by jturkel** [comment]
@coorasse - I'm closing this issue since I can't reproduce it. Please reopen it if you can provide a reproducible test case.
