### ISSUE TITLE
Ignore has one associations that relies on LIMIT 1

### ISSUE THREAD

**Issue by sobrinho** [salsify/goldiloader#61]
Hi there,

We can almost detect that relies on LIMIT 1 by checking if an order was specified.

Example:

```ruby
class Order < ApplicationRecord
  has_many :payments
  has_one :last_payment, through: :payments, order: 'paid_at desc'
end
```

If the order is specified, we are certain that the database may have more than one record.

In that case, we can simply do not auto include because we know that may trigger a problem.

Wdyt?

**Comment by jturkel** [comment]
Sounds reasonable. Want to take a crack at a PR?

**Comment by sobrinho** [comment]
Yes, sure!

I will work on this.
