### ISSUE TITLE
Plans to release a version to enable Rails 6.1 as dependency?

### ISSUE THREAD

**Issue by pedrofurtado** [salsify/goldiloader#98]
Hey guys!

Is there any plans to release a version to enable Rails 6.1 as dependency?

**Comment by jturkel** [comment]
I'm working on a release right now :) It should be out this morning.

**Comment by pedrofurtado** [comment]
Yeeeesssssss! Thank you so much 🍻

**Comment by jturkel** [comment]
Rails 6.1 support was released in goldiloader 3.2.0 🎉
